COMPILATOR := gcc
OPTIONS := -Og -Wall -Wextra -g -I data_structures -I lexing -I parsing

lexing_test.out: bin/lexing_test.o bin/lexer.o bin/token.o bin/parser.o
	$(COMPILATOR) $(OPTIONS) $^ -o $@

bin/lexing_test.o: tests/lexing_test.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@

bin/lexer.o: lexing/lexer.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@

bin/token.o: data_structures/token.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@

bin/parser.o: parsing/parser.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@
