COMPILATOR := gcc
OPTIONS := -Og -Wall -Wextra -g -I data_structures -I lexing -I parsing

parsing_test.out: bin/parsing_test.o bin/lexer.o bin/token.o bin/parser.o bin/parsing_node.o
	$(COMPILATOR) $(OPTIONS) $^ -o $@

bin/parsing_test.o: tests/parsing_test.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@

bin/lexer.o: lexing/lexer.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@

bin/token.o: data_structures/token.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@

bin/parser.o: parsing/parser.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@

bin/parsing_node.o: data_structures/parsing_node.c
	$(COMPILATOR) -c $(OPTIONS) $< -o $@

